# Generated by Django 3.0.8 on 2020-10-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('aadhar', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address_id', models.IntegerField()),
                ('contact_id', models.IntegerField(unique=True)),
                ('email_id', models.CharField(max_length=20)),
            ],
        ),
    ]
