# Generated by Django 3.1.2 on 2020-10-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('main', '0002_auto_20201025_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_morbidity',
            name='aadhaar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.citizen'),
        ),
        migrations.AlterField(
            model_name='general_health',
            name='aadhaar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.citizen'),
        ),
        migrations.AlterField(
            model_name='traits',
            name='aadhaar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.citizen'),
        ),
    ]
