# Generated by Django 3.1.2 on 2020-10-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201025_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_health',
            old_name='last_check_date',
            new_name='last_checkup_date',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.address'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contact'),
        ),
    ]
