# Generated by Django 3.1.2 on 2020-10-26 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201026_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='address_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.address'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='contact_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.contact'),
        ),
    ]
