# Generated by Django 3.1.2 on 2020-10-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201026_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
