# Generated by Django 3.1.2 on 2020-10-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201026_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
